name: build-historic
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The TeXLive version to be built
        required: true
      deploy:
        type: boolean
        description: Whether to deploy the build images
jobs:
  build_historic:
    strategy:
      matrix:
        os: [debian, alpine]
    name: Build Historic TeXLive [${{ matrix.os}}]
    runs-on: ubuntu-latest
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}
          build-args: version=${{ inputs.version }}
          tags: texlive-histroic-${{ matrix.os }}
          load: true
      - name: Test pdflatex
        run: |
          docker run --rm "texlive-histroic-$OS" pdflatex --version
          cat <<EOF >ref.bib
          @book{knuth1997,
            author    = {Donald E. Knuth},
            title     = {The Art of Computer Programming},
            volume    = {1},
            publisher = {Addison-Wesley},
            year      = {1997}
          }
          EOF
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \usepackage[style=authoryear]{biblatex}
          \addbibresource{ref.bib}
          \begin{document}
          Test~\cite{knuth1997}.

          \printbibliography
          \end{document}
          EOF
          docker run --rm -v "$(pwd):/data" -w /data "texlive-histroic-$OS" \
            latexmk -g -pdf -halt-on-error -interaction=nonstopmode test.tex
          file test.pdf | grep -q ' PDF '
      - name: Test latexindent
        run: |
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd):/data" -w /data "texlive-histroic-$OS" latexindent test.tex
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        if: "inputs.deploy"
      - name: Deploy
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}
          build-args: version=${{ inputs.version }}
          tags: ghcr.io/xu-cheng/texlive-histroic-${{ matrix.os }}:${{ inputs.version }}
          push: true
        if: "inputs.deploy"
